### ISSUE TITLE
About parameters modify

### ISSUE THREAD

**Issue by dovanchan** [dsanno/chainer-neural-style#6]
Hi:
https://github.com/cysmith/neural-style-tf/blob/master/neural_style.py  
In this implement of neural-style parameters:
parser.add_argument('--content_layers', nargs='+', type=str, 
    default=['conv4_2']:

parser.add_argument('--style_layers', nargs='+', type=str,
    default=['relu1_1', 'relu2_1', 'relu3_1', 'relu4_1', 'relu5_1'],

content layer is conv4_2,style layer is 'relu1_1', 'relu2_1', 'relu3_1', 'relu4_1', 'relu5_1'

So,If I wanna use the TF's parameters in your chainer implement:

parser.add_argument('--content_layers', default='3_3,4_3', type=str,
                        help='content layer names')
    parser.add_argument('--style_layers', default='1_2,2_2,3_3,4_3', type=str,
                        help='style layer names') 

How to set the content layers and style layers~ Thank you~

**Comment by dsanno** [comment]
My implementation supports only relu layers.
You can specify content layers with `--content_layers 4_2` and style layers with `--style_layers 1_1,2_1,3_1,4_1,5_1`
This is equivalent to ['relu4_2'] for content layers and ['relu1_1', 'relu2_1', 'relu3_1', 'relu4_1', 'relu5_1'] for style layers.

Torch implementation use 'relu_4_2' for content layer as default, so I think setting above will work.
see https://github.com/jcjohnson/neural-style/blob/master/neural_style.lua#L48 for Torch implementation.

**Comment by dovanchan** [comment]
If I wanna use conv4_2 for content layer,How you do that?

**Comment by dsanno** [comment]
Fix `__call__` of `VGG19`
https://github.com/dsanno/chainer-neural-style/blob/master/src/net.py#L93
so that stored layers includes conv layers:
```
        for layer_name in layer_names:
            if layer_name == 'pool':
                h = F.max_pooling_2d(h, 2, stride=2)
            else:
                h = self['conv' + layer_name](h)
                layers['conv' + layer_name] = h
                h = F.relu(h)
                layers[layer_name] = h
return layers
```

and use conv4_2 with `--content_layers conv4_2`.

**Comment by dovanchan** [comment]
In tensorflow,we can use these script for limit the GPU memory usage;

gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))

Do you know what's script for limit GPU usage in chainer?

**Comment by dsanno** [comment]
That is Chainer issue.
Ask Chainer developers.

**Comment by dovanchan** [comment]
Thank you for your contribution and help~
